In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('titanic.csv')

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [101]:
df.shape

(891, 12)

In [5]:
df["Survived"].value_counts()/df.shape[0]

0    0.616162
1    0.383838
Name: Survived, dtype: float64

In [6]:
df["Survived"].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [48]:
xtest = df[df['Survived']==1].sample(n=5)[['Pclass','Fare','Age']].fillna(56)

In [49]:
xtest.values

array([[  2.    ,  13.    ,  28.    ],
       [  3.    ,  19.2583,   0.75  ],
       [  2.    ,  13.    ,  24.    ],
       [  1.    , 227.525 ,  42.    ],
       [  2.    ,  29.    ,   0.83  ]])

In [7]:
df1= df[df['Survived']==1].sample(n=6)

In [8]:
df1

PassengerId  Survived  Pclass  \
879          880         1       1   
52            53         1       1   
224          225         1       1   
198          199         1       3   
632          633         1       1   
489          490         1       3   

                                              Name     Sex   Age  SibSp  \
879  Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
52        Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.0      1   
224                   Hoyt, Mr. Frederick Maxfield    male  38.0      1   
198               Madigan, Miss. Margaret "Maggie"  female   NaN      0   
632                      Stahelin-Maeglin, Dr. Max    male  32.0      0   
489          Coutts, Master. Eden Leslie "Neville"    male   9.0      1   

     Parch      Ticket     Fare Cabin Embarked  
879      1       11767  83.1583   C50        C  
52       0    PC 17572  76.7292   D33        C  
224      0       19943  90.0000   C93        S  
198      0      370370   7.7500   NaN        Q  
632      0       13214  30.5000   B50        C  
489      1  C.A. 37671  15.9000   NaN        S

In [9]:
df1 = pd.concat([df1,df[df['Survived']==0]])
df1.shape

(555, 12)

In [11]:
df1["Survived"].value_counts()/df1.shape[0]

0    0.989189
1    0.010811
Name: Survived, dtype: float64

In [17]:
df1 = df1.reset_index(drop=True)
df1.head()

PassengerId  Survived  Pclass  \
0          880         1       1   
1           53         1       1   
2          225         1       1   
3          199         1       3   
4          633         1       1   

                                            Name     Sex   Age  SibSp  Parch  \
0  Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0      1   
1       Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.0      1      0   
2                   Hoyt, Mr. Frederick Maxfield    male  38.0      1      0   
3               Madigan, Miss. Margaret "Maggie"  female   NaN      0      0   
4                      Stahelin-Maeglin, Dr. Max    male  32.0      0      0   

     Ticket     Fare Cabin Embarked  
0     11767  83.1583   C50        C  
1  PC 17572  76.7292   D33        C  
2     19943  90.0000   C93        S  
3    370370   7.7500   NaN        Q  
4     13214  30.5000   B50        C

In [30]:
df1['Age'].median

<bound method NDFrame._add_numeric_operations.<locals>.median of 0      56.0
1      49.0
2      38.0
3       NaN
4      32.0
       ... 
550    25.0
551    39.0
552    27.0
553     NaN
554    32.0
Name: Age, Length: 555, dtype: float64>

In [32]:
df1['Age'].fillna(56,inplace=True)

In [33]:
df1.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          483
Embarked         0
dtype: int64

In [34]:
X , Y = df1[['Pclass','Fare','Age']], df1['Survived']

In [35]:
X.shape, Y.shape

((555, 3), (555,))

In [36]:
from imblearn.over_sampling import SMOTE

In [37]:
s = SMOTE()

In [38]:
features, label = s.fit_resample(X,Y)

In [39]:
features.shape

(1098, 3)

In [40]:
label.shape

(1098,)

In [42]:
label.value_counts()

1    549
0    549
Name: Survived, dtype: int64

In [43]:
 from sklearn.ensemble import IsolationForest

In [44]:
isolation = IsolationForest()

In [45]:
classifier = isolation.fit(X)

In [50]:
classifier.predict(xtest.values)

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but IsolationForest was fitted with feature names
  warnings.warn(


array([ 1, -1,  1, -1, -1])

In [55]:
from keras.models import Sequential
from keras.layers import Dense,Dropout, LSTM , SimpleRNN, Embedding, Input

In [57]:
model = Sequential()
model.add(Input(shape = (3,)))
model.add(Dense(16, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(3))

In [58]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_5 (Dense)             (None, 16)                64        
                                                                 
 dense_6 (Dense)             (None, 10)                170       
                                                                 
 dense_7 (Dense)             (None, 16)                176       
                                                                 
 dense_8 (Dense)             (None, 3)                 51        
                                                                 
Total params: 461 (1.80 KB)
Trainable params: 461 (1.80 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [59]:
model.compile(loss='mean_squared_error',metrics=['accuracy'])

In [61]:
data = df[df['Survived']==0][['Pclass','Fare','Age']]
data['Age'].fillna(56,inplace=True)

In [62]:
data.shape

(549, 3)

In [63]:
data.values

array([[ 3.    ,  7.25  , 22.    ],
       [ 3.    ,  8.05  , 35.    ],
       [ 3.    ,  8.4583, 56.    ],
       ...,
       [ 2.    , 13.    , 27.    ],
       [ 3.    , 23.45  , 56.    ],
       [ 3.    ,  7.75  , 32.    ]])

In [64]:
model.fit(data.values, data.values ,batch_size=12,epochs=10)

Epoch 1/10
46/46 [==============================] - 2s 4ms/step - loss: 567.9599 - accuracy: 0.9016
Epoch 2/10
46/46 [==============================] - 0s 4ms/step - loss: 176.5673 - accuracy: 0.9344
Epoch 3/10
46/46 [==============================] - 0s 3ms/step - loss: 83.7390 - accuracy: 0.9417
Epoch 4/10
46/46 [==============================] - 0s 4ms/step - loss: 32.5638 - accuracy: 0.9709
Epoch 5/10
46/46 [==============================] - 0s 6ms/step - loss: 10.8222 - accuracy: 0.9872
Epoch 6/10
46/46 [==============================] - 0s 6ms/step - loss: 5.1341 - accuracy: 0.9909
Epoch 7/10
46/46 [==============================] - 0s 4ms/step - loss: 2.8039 - accuracy: 0.9891
Epoch 8/10
46/46 [==============================] - 0s 8ms/step - loss: 1.4677 - accuracy: 0.9927
Epoch 9/10
46/46 [==============================] - 0s 5ms/step - loss: 0.8596 - accuracy: 0.9872
Epoch 10/10
46/46 [==============================] - 0s 6ms/step - loss: 0.6775 - accuracy: 0.9945


In [70]:
pred = model.predict(data.values)

18/18 [==============================] - 0s 3ms/step


In [77]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
import numpy as np

In [72]:
mean_absolute_error(data.values, pred)

0.44876015705428274

In [73]:
mean_squared_error(data.values, pred)

0.5293634254031835

In [86]:
err = data.values -pred

In [87]:
err

array([[ 0.86956358,  0.14732075,  0.06060791],
       [ 0.3652482 ,  0.00221901,  0.0414238 ],
       [ 0.06489611, -0.11701643,  0.55564117],
       ...,
       [ 0.13976252,  0.0041275 ,  0.32153511],
       [ 0.07330751,  0.01921196,  0.51650238],
       [ 0.44199324,  0.02518892,  0.00442314]])

In [91]:
err.shape

(549, 3)

In [92]:
error_rate = np.mean(err,axis=1)

In [93]:
len(error_rate)

549

In [97]:
error_rate.mean()

0.16690336535314249

In [94]:
data = df[df['Survived']==1][['Pclass','Fare','Age']]
data['Age'].fillna(56,inplace=True)

In [95]:
pred_anomaly = model.predict(data.values)

11/11 [==============================] - 0s 5ms/step


In [98]:
err_an = data.values -pred_anomaly

In [99]:
error_rate_an = np.mean(err_an,axis=1)
error_rate_an

array([-3.19288864e-01,  2.95758502e-01, -3.23755868e-01,  3.91115405e-01,
        6.70255997e-02,  4.00290434e-01, -3.31606134e-01, -2.56199360e-01,
       -1.76663240e-01,  1.90615845e-01,  3.24201584e-03,  4.42260120e-01,
       -2.03104774e-01,  3.25871690e-01,  1.82805862e-01,  2.78043368e-02,
        1.84403578e-01,  1.90565624e-01,  4.16594011e-01,  2.10492879e-01,
        4.18204671e-01,  1.84403578e-01, -4.38308042e-01,  8.98515781e-02,
       -3.42769464e-01,  1.65551861e-01,  2.65153448e-01, -2.27509022e-01,
       -7.58346532e-03,  2.19022433e-02,  4.29955618e-01,  1.30010122e-01,
       -1.27331112e-01,  3.74129327e-01,  2.87306309e-01,  1.83959198e-01,
        1.65068984e-01,  4.14052359e-01,  9.42284465e-01, -3.17963264e-02,
        4.25458352e-02,  3.95825036e-01,  1.84107908e-01,  2.28617636e-01,
        3.62814267e-02,  4.19611277e-01,  3.11149508e-01,  1.63065364e-01,
        8.98515781e-02, -1.94900129e-01,  3.77457301e-01,  3.63849076e-01,
        2.69005547e-01,  

In [100]:
error_rate_an.mean()

0.10087282685917505