In [2]:
import numpy as np

In [3]:
np.array([1,2,3])+1

array([2, 3, 4])

In [ ]:
# Numpy basically uses two concepts vectorization and broadcasting 

In [5]:
np.array([1,2,3])+np.array([1,2,3])+np.array([1,2,3])

array([3, 6, 9])

In [6]:
[1,2,3]+[1]

[1, 2, 3, 1]

In [1]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()
import pandas as pd
from nltk.stem import PorterStemmer
import nltk
import contractions
import re

stop_words = nltk.corpus.stopwords.words('english')

In [ ]:
import wanrnings
warnings.filterwarnings("ignore")

In [2]:
import numpy as np 

In [3]:
df = pd.read_csv('TwitterData.csv')

In [4]:
df.head()

sentiment                                            content  \
0       empty  @tiffanylue i know  i was listenin to bad habi...   
1     sadness  Layin n bed with a headache  ughhhh...waitin o...   
2     sadness                Funeral ceremony...gloomy friday...   
3  enthusiasm               wants to hang out with friends SOON!   
4     neutral  @dannycastillo We want to trade with someone w...   

                                                text  
0  know  wa listenin bad habit earlier start frea...  
1            layin n bed headach  ughhhh waitin call  
2                       funer ceremoni gloomi friday  
3                              want hang friend soon  
4            want trade someon ha houston ticket one

In [5]:
df.isnull().sum()

sentiment      0
content        0
text         201
dtype: int64

In [6]:
df.dropna(inplace=True)

In [8]:
df['sentiment'].value_counts()

neutral       8508
worry         8439
happiness     5205
sadness       5155
love          3837
surprise      2182
fun           1775
relief        1524
hate          1322
empty          805
enthusiasm     758
boredom        179
anger          110
Name: sentiment, dtype: int64

In [9]:
df1 = df[df['sentiment'].isin(['happiness','sadness'])]

In [10]:
df1.shape

(10360, 3)

In [11]:
df1['sentiment'].value_counts()

happiness    5205
sadness      5155
Name: sentiment, dtype: int64

In [12]:
labels_mapping = {'sadness':0,'happiness':1}
df1['label'] = df1['sentiment'].apply(lambda x: labels_mapping[x])

C:\Users\Hp\AppData\Local\Temp\ipykernel_9400\1490432486.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['label'] = df1['sentiment'].apply(lambda x: labels_mapping[x])


In [13]:
df1.head()

sentiment                                            content  \
1   sadness  Layin n bed with a headache  ughhhh...waitin o...   
2   sadness                Funeral ceremony...gloomy friday...   
6   sadness  I should be sleep, but im not! thinking about ...   
8   sadness            @charviray Charlene my love. I miss you   
9   sadness         @kelcouch I'm sorry  at least it's Friday?   

                                                text  label  
1            layin n bed headach  ughhhh waitin call      0  
2                       funer ceremoni gloomi friday      0  
6  sleep think old friend want marri damn amp wan...      0  
8                                  charlen love miss      0  
9                                sorri  least friday      0

In [14]:
df1.tail()

sentiment                                            content  \
39986  happiness  going to watch boy in the striped pj's hope i ...   
39987  happiness  gave the bikes a thorough wash, degrease it an...   
39988  happiness  had SUCH and AMAZING time last night, McFly we...   
39994  happiness                      Succesfully following Tayla!!   
39998  happiness  @niariley WASSUP BEAUTIFUL!!! FOLLOW ME!!  PEE...   

                                                    text  label  
39986                    go watch boy stripe pj hope cri      1  
39987  gave bike thorough wash degreas greas think re...      1  
39988                  amaz time last night mcfli incred      1  
39994                                succes follow tayla      1  
39998  wassup beauti follow  peep new hit singl wwwmy...      1

In [33]:
df1 = df1.reset_index(drop=True)

In [34]:
df1.head()

sentiment                                            content  \
0   sadness  Layin n bed with a headache  ughhhh...waitin o...   
1   sadness                Funeral ceremony...gloomy friday...   
2   sadness  I should be sleep, but im not! thinking about ...   
3   sadness            @charviray Charlene my love. I miss you   
4   sadness         @kelcouch I'm sorry  at least it's Friday?   

                                                text  label  
0            layin n bed headach  ughhhh waitin call      0  
1                       funer ceremoni gloomi friday      0  
2  sleep think old friend want marri damn amp wan...      0  
3                                  charlen love miss      0  
4                                sorri  least friday      0

In [17]:
doc= list(df1['text'].values)

In [18]:
df1.shape, len(doc)

((10360, 4), 10360)

## Using Glove to create embeddings

In [15]:
import spacy

nlp =spacy.load('en_core_web_lg')

vectors= len(nlp.vocab.vectors)

In [16]:
def average_word_embedding(doc,feature_size):
    vector = np.zeros((feature_size),dtype='float64')
    total_words= len(doc)
    for word in doc:
        vector = np.add(vector,nlp(word).vector)
    vector = np.divide(vector,total_words)
    return vector

In [20]:
features = []
for sent in doc:
    features.append(average_word_embedding(sent.split(' '),300))

In [21]:
features = np.array(features)

In [26]:
data = pd.DataFrame(features)

In [27]:
data.shape

(10360, 300)

In [28]:
df1.label.shape

(10360,)

In [35]:
# combining features with labels 
data1 = pd.concat([data,df1['label']],axis=1)

In [36]:
data1.shape

(10360, 301)

In [37]:
data1.head()

0         1         2         3         4         5         6  \
0  0.637036  1.883381  0.381798 -0.108581  0.435688 -0.162045 -1.190415   
1  0.081693 -0.330775 -0.453375  0.457775  0.546300  0.025453 -0.199600   
2  0.173242  2.176264 -3.299218 -2.864649  0.207435  0.548493  2.856654   
3  1.070600 -0.115300 -1.891495 -3.116567 -0.045237  0.014267  2.636277   
4 -0.172557  0.241075 -0.716475  0.754475  1.587325  1.477227  1.511325   

          7         8         9  ...       291       292       293       294  \
0 -0.690042 -1.382248  0.849650  ... -0.082561  1.888970 -2.321531 -1.793487   
1  0.383875  0.092880  0.223795  ...  0.539275  0.564000 -0.222125 -1.181150   
2  2.648244 -1.013542  0.994068  ... -0.225290 -0.776103 -2.294959 -1.611076   
3  1.919633  0.581767  0.621667  ...  0.592357 -0.244533 -3.423867 -0.583006   
4  1.590100  0.324245  0.543195  ...  0.740805  0.791185 -0.453410 -2.349175   

        295       296       297       298       299  label  
0 -1.245097 -2.349115  0.133911 -0.878310  1.327500      0  
1  0.347950  0.086352 -0.430075  0.271025  0.197190      0  
2 -2.105731 -1.346295  3.014289 -1.911785  0.420806      0  
3 -1.842900 -1.587190  2.539000 -3.421400 -1.005233      0  
4  1.477550  0.247835 -0.648282 -0.812025  0.410740      0  

[5 rows x 301 columns]

### Train Test Split and Model Training 

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [42]:
X  = data1.iloc[:,:-1]
Y = data1.iloc[:,-1:]

In [43]:
X.shape, Y.shape

((10360, 300), (10360, 1))

In [44]:
xtrain, xtest, ytrain, ytest = train_test_split(X, Y, test_size=0.20, random_state= 90, stratify=Y)

In [45]:
xtrain.shape, xtest.shape, ytrain.shape, ytest.shape

((8288, 300), (2072, 300), (8288, 1), (2072, 1))

In [46]:
lr = LogisticRegression()
lr.fit(xtrain,ytrain)


C:\Users\Hp\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [47]:
rf = RandomForestClassifier()
rf.fit(xtrain,ytrain)

C:\Users\Hp\AppData\Local\Temp\ipykernel_9400\2790016137.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(xtrain,ytrain)


RandomForestClassifier()

In [48]:
lr_labels = lr.predict(xtest)
rf_labels = rf.predict(xtest)

In [50]:
len(lr_labels)

2072

In [51]:
len(rf_labels)

2072

In [52]:
len(ytest)

2072

In [53]:
lr_accuracy = accuracy_score(ytest,lr_labels)
rf_accuracy = accuracy_score(ytest,rf_labels)

In [54]:
lr_accuracy

0.7562741312741312

In [55]:
rf_accuracy

0.7200772200772201

In [57]:
print(classification_report(ytest,lr_labels))

              precision    recall  f1-score   support

           0       0.76      0.75      0.75      1031
           1       0.75      0.76      0.76      1041

    accuracy                           0.76      2072
   macro avg       0.76      0.76      0.76      2072
weighted avg       0.76      0.76      0.76      2072



In [ ]:
s ='I am happy'

In [1]:
lr.predict()

NameError: name 'lr' is not defined

In [ ]:
#Saving this and load the model to do the prediction 

In [58]:
import pickle

In [59]:
with open('Logisticmodel.pkl','wb') as file:
    pickle.dump(lr,file)

In [62]:
with open('Logisticmodel.pkl','rb') as file:
    lr2 = pickle.load(file)

In [63]:
lr2

LogisticRegression()

In [64]:
lr_labels = lr2.predict(xtest)

In [65]:
lr_labels

array([1, 1, 1, ..., 0, 1, 0], dtype=int64)